/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAffiliateProgramsRouteImport } from './routes/_authenticated.affiliate-programs'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated.billing'
import { Route as AuthenticatedContentRouteImport } from './routes/_authenticated.content'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedIntakeRouteImport } from './routes/_authenticated.intake'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated.personas'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated.plan'
import { Route as AuthenticatedPublishingRouteImport } from './routes/_authenticated.publishing'
import { Route as AuthenticatedStrategyRouteImport } from './routes/_authenticated.strategy'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated.studio'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated.upgrade'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as RCodeRouteImport } from './routes/r.$code'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedCalendarIndexRouteImport } from './routes/_authenticated.calendar.index'
import { Route as AuthenticatedCalendarDateRouteImport } from './routes/_authenticated.calendar.$date'
import { Route as AuthenticatedCampaignsIndexRouteImport } from './routes/_authenticated.campaigns.index'
import { Route as AuthenticatedCampaignsIdRouteImport } from './routes/_authenticated.campaigns.$id'
import { Route as AuthenticatedMediaPlanIdRouteImport } from './routes/_authenticated.media-plan.$id'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated.products.index'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated.products.$id'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated.products.new'
import { Route as AuthenticatedSettingsIntegrationsRouteImport } from './routes/_authenticated.settings.integrations'
import { Route as AuthenticatedVideosIndexRouteImport } from './routes/_authenticated.videos.index'
import { Route as AuthenticatedVideosIdRouteImport } from './routes/_authenticated.videos.$id'
import { Route as ApiMediaVariantIdRouteImport } from './routes/api/media.$variantId'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks.stripe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAffiliateProgramsRoute =
  AuthenticatedAffiliateProgramsRouteImport.update({
    id: '/affiliate-programs',
    path: '/affiliate-programs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContentRoute = AuthenticatedContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntakeRoute = AuthenticatedIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPublishingRoute = AuthenticatedPublishingRouteImport.update({
  id: '/publishing',
  path: '/publishing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStrategyRoute = AuthenticatedStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const RCodeRoute = RCodeRouteImport.update({
  id: '/r/$code',
  path: '/r/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCalendarIndexRoute =
  AuthenticatedCalendarIndexRouteImport.update({
    id: '/calendar/',
    path: '/calendar/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCalendarDateRoute =
  AuthenticatedCalendarDateRouteImport.update({
    id: '/calendar/$date',
    path: '/calendar/$date',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIndexRoute =
  AuthenticatedCampaignsIndexRouteImport.update({
    id: '/campaigns/',
    path: '/campaigns/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCampaignsIdRoute =
  AuthenticatedCampaignsIdRouteImport.update({
    id: '/campaigns/$id',
    path: '/campaigns/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMediaPlanIdRoute =
  AuthenticatedMediaPlanIdRouteImport.update({
    id: '/media-plan/$id',
    path: '/media-plan/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIntegrationsRoute =
  AuthenticatedSettingsIntegrationsRouteImport.update({
    id: '/settings/integrations',
    path: '/settings/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVideosIndexRoute =
  AuthenticatedVideosIndexRouteImport.update({
    id: '/videos/',
    path: '/videos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVideosIdRoute = AuthenticatedVideosIdRouteImport.update({
  id: '/videos/$id',
  path: '/videos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiMediaVariantIdRoute = ApiMediaVariantIdRouteImport.update({
  id: '/api/media/$variantId',
  path: '/api/media/$variantId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/affiliate-programs': typeof AuthenticatedAffiliateProgramsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/publishing': typeof AuthenticatedPublishingRoute
  '/strategy': typeof AuthenticatedStrategyRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/calendar/$date': typeof AuthenticatedCalendarDateRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/media-plan/$id': typeof AuthenticatedMediaPlanIdRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/videos/$id': typeof AuthenticatedVideosIdRoute
  '/api/media/$variantId': typeof ApiMediaVariantIdRoute
  '/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/videos/': typeof AuthenticatedVideosIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/affiliate-programs': typeof AuthenticatedAffiliateProgramsRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/content': typeof AuthenticatedContentRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/intake': typeof AuthenticatedIntakeRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/publishing': typeof AuthenticatedPublishingRoute
  '/strategy': typeof AuthenticatedStrategyRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/calendar/$date': typeof AuthenticatedCalendarDateRoute
  '/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/media-plan/$id': typeof AuthenticatedMediaPlanIdRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/videos/$id': typeof AuthenticatedVideosIdRoute
  '/api/media/$variantId': typeof ApiMediaVariantIdRoute
  '/calendar': typeof AuthenticatedCalendarIndexRoute
  '/campaigns': typeof AuthenticatedCampaignsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/videos': typeof AuthenticatedVideosIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/auth': typeof AuthRoute
  '/cookies': typeof CookiesRoute
  '/guides': typeof GuidesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/industries': typeof IndustriesRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refunds': typeof RefundsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/affiliate-programs': typeof AuthenticatedAffiliateProgramsRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/content': typeof AuthenticatedContentRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/intake': typeof AuthenticatedIntakeRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/publishing': typeof AuthenticatedPublishingRoute
  '/_authenticated/strategy': typeof AuthenticatedStrategyRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/r/$code': typeof RCodeRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/calendar/$date': typeof AuthenticatedCalendarDateRoute
  '/_authenticated/campaigns/$id': typeof AuthenticatedCampaignsIdRoute
  '/_authenticated/media-plan/$id': typeof AuthenticatedMediaPlanIdRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/settings/integrations': typeof AuthenticatedSettingsIntegrationsRoute
  '/_authenticated/videos/$id': typeof AuthenticatedVideosIdRoute
  '/api/media/$variantId': typeof ApiMediaVariantIdRoute
  '/_authenticated/calendar/': typeof AuthenticatedCalendarIndexRoute
  '/_authenticated/campaigns/': typeof AuthenticatedCampaignsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/videos/': typeof AuthenticatedVideosIndexRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliate-disclosure'
    | '/auth'
    | '/cookies'
    | '/guides'
    | '/how-it-works'
    | '/industries'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/affiliate-programs'
    | '/billing'
    | '/content'
    | '/dashboard'
    | '/intake'
    | '/personas'
    | '/plan'
    | '/publishing'
    | '/strategy'
    | '/studio'
    | '/upgrade'
    | '/checkout/return'
    | '/guides/$slug'
    | '/r/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/calendar/$date'
    | '/campaigns/$id'
    | '/media-plan/$id'
    | '/products/$id'
    | '/products/new'
    | '/settings/integrations'
    | '/videos/$id'
    | '/api/media/$variantId'
    | '/calendar/'
    | '/campaigns/'
    | '/products/'
    | '/videos/'
    | '/api/public/webhooks/stripe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate-disclosure'
    | '/auth'
    | '/cookies'
    | '/guides'
    | '/how-it-works'
    | '/industries'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/affiliate-programs'
    | '/billing'
    | '/content'
    | '/dashboard'
    | '/intake'
    | '/personas'
    | '/plan'
    | '/publishing'
    | '/strategy'
    | '/studio'
    | '/upgrade'
    | '/checkout/return'
    | '/guides/$slug'
    | '/r/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/calendar/$date'
    | '/campaigns/$id'
    | '/media-plan/$id'
    | '/products/$id'
    | '/products/new'
    | '/settings/integrations'
    | '/videos/$id'
    | '/api/media/$variantId'
    | '/calendar'
    | '/campaigns'
    | '/products'
    | '/videos'
    | '/api/public/webhooks/stripe'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/affiliate-disclosure'
    | '/auth'
    | '/cookies'
    | '/guides'
    | '/how-it-works'
    | '/industries'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/refunds'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/affiliate-programs'
    | '/_authenticated/billing'
    | '/_authenticated/content'
    | '/_authenticated/dashboard'
    | '/_authenticated/intake'
    | '/_authenticated/personas'
    | '/_authenticated/plan'
    | '/_authenticated/publishing'
    | '/_authenticated/strategy'
    | '/_authenticated/studio'
    | '/_authenticated/upgrade'
    | '/checkout/return'
    | '/guides/$slug'
    | '/r/$code'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/calendar/$date'
    | '/_authenticated/campaigns/$id'
    | '/_authenticated/media-plan/$id'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/settings/integrations'
    | '/_authenticated/videos/$id'
    | '/api/media/$variantId'
    | '/_authenticated/calendar/'
    | '/_authenticated/campaigns/'
    | '/_authenticated/products/'
    | '/_authenticated/videos/'
    | '/api/public/webhooks/stripe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  AuthRoute: typeof AuthRoute
  CookiesRoute: typeof CookiesRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  IndustriesRoute: typeof IndustriesRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundsRoute: typeof RefundsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  RCodeRoute: typeof RCodeRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiMediaVariantIdRoute: typeof ApiMediaVariantIdRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/affiliate-programs': {
      id: '/_authenticated/affiliate-programs'
      path: '/affiliate-programs'
      fullPath: '/affiliate-programs'
      preLoaderRoute: typeof AuthenticatedAffiliateProgramsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/content': {
      id: '/_authenticated/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof AuthenticatedContentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intake': {
      id: '/_authenticated/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof AuthenticatedIntakeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/publishing': {
      id: '/_authenticated/publishing'
      path: '/publishing'
      fullPath: '/publishing'
      preLoaderRoute: typeof AuthenticatedPublishingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/strategy': {
      id: '/_authenticated/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof AuthenticatedStrategyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/r/$code': {
      id: '/r/$code'
      path: '/r/$code'
      fullPath: '/r/$code'
      preLoaderRoute: typeof RCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/calendar/': {
      id: '/_authenticated/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof AuthenticatedCalendarIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar/$date': {
      id: '/_authenticated/calendar/$date'
      path: '/calendar/$date'
      fullPath: '/calendar/$date'
      preLoaderRoute: typeof AuthenticatedCalendarDateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/': {
      id: '/_authenticated/campaigns/'
      path: '/campaigns'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AuthenticatedCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns/$id': {
      id: '/_authenticated/campaigns/$id'
      path: '/campaigns/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AuthenticatedCampaignsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media-plan/$id': {
      id: '/_authenticated/media-plan/$id'
      path: '/media-plan/$id'
      fullPath: '/media-plan/$id'
      preLoaderRoute: typeof AuthenticatedMediaPlanIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/integrations': {
      id: '/_authenticated/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AuthenticatedSettingsIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos/': {
      id: '/_authenticated/videos/'
      path: '/videos'
      fullPath: '/videos/'
      preLoaderRoute: typeof AuthenticatedVideosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/videos/$id': {
      id: '/_authenticated/videos/$id'
      path: '/videos/$id'
      fullPath: '/videos/$id'
      preLoaderRoute: typeof AuthenticatedVideosIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/media/$variantId': {
      id: '/api/media/$variantId'
      path: '/api/media/$variantId'
      fullPath: '/api/media/$variantId'
      preLoaderRoute: typeof ApiMediaVariantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAffiliateProgramsRoute: typeof AuthenticatedAffiliateProgramsRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedContentRoute: typeof AuthenticatedContentRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIntakeRoute: typeof AuthenticatedIntakeRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedPublishingRoute: typeof AuthenticatedPublishingRoute
  AuthenticatedStrategyRoute: typeof AuthenticatedStrategyRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedCalendarDateRoute: typeof AuthenticatedCalendarDateRoute
  AuthenticatedCampaignsIdRoute: typeof AuthenticatedCampaignsIdRoute
  AuthenticatedMediaPlanIdRoute: typeof AuthenticatedMediaPlanIdRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedSettingsIntegrationsRoute: typeof AuthenticatedSettingsIntegrationsRoute
  AuthenticatedVideosIdRoute: typeof AuthenticatedVideosIdRoute
  AuthenticatedCalendarIndexRoute: typeof AuthenticatedCalendarIndexRoute
  AuthenticatedCampaignsIndexRoute: typeof AuthenticatedCampaignsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedVideosIndexRoute: typeof AuthenticatedVideosIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAffiliateProgramsRoute: AuthenticatedAffiliateProgramsRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedContentRoute: AuthenticatedContentRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIntakeRoute: AuthenticatedIntakeRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedPublishingRoute: AuthenticatedPublishingRoute,
  AuthenticatedStrategyRoute: AuthenticatedStrategyRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedCalendarDateRoute: AuthenticatedCalendarDateRoute,
  AuthenticatedCampaignsIdRoute: AuthenticatedCampaignsIdRoute,
  AuthenticatedMediaPlanIdRoute: AuthenticatedMediaPlanIdRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedSettingsIntegrationsRoute:
    AuthenticatedSettingsIntegrationsRoute,
  AuthenticatedVideosIdRoute: AuthenticatedVideosIdRoute,
  AuthenticatedCalendarIndexRoute: AuthenticatedCalendarIndexRoute,
  AuthenticatedCampaignsIndexRoute: AuthenticatedCampaignsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedVideosIndexRoute: AuthenticatedVideosIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  AuthRoute: AuthRoute,
  CookiesRoute: CookiesRoute,
  GuidesRoute: GuidesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  IndustriesRoute: IndustriesRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundsRoute: RefundsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  RCodeRoute: RCodeRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiMediaVariantIdRoute: ApiMediaVariantIdRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
